production:
  heartbeat_monitors:
    class: HeartbeatMonitorsJob
    queue: background
    priority: 1
    schedule: every 10 minutes
  uptime_monitors:
    class: UptimeMonitorsJob
    queue: background
    priority: 1
    schedule: every minute
  aggregate_samples:
    class: AggregateSamplesJob
    queue: background
    priority: 1
    schedule: every 10 minutes
  cleanup_samples:
    class: CleanupSamplesJob
    queue: background
    priority: 1
    schedule: every 10 minutes
